/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package org.itson.presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * @author Victor y Samuel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Este método ubica la ventana en el centro de la pantalla
     */
    private void centraVentana() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        Dimension frameSize = getSize();
        
        if(frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        
        if(frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        
        setLocation((screenSize.height - frameSize.height)/2, (screenSize.width - frameSize.width)/2);
    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        centraVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuBar = new javax.swing.JMenuBar();
        tramitesMenu = new javax.swing.JMenu();
        licenciaTramitesMenu = new javax.swing.JMenuItem();
        placasTramitesMenu = new javax.swing.JMenuItem();
        consultasMenu = new javax.swing.JMenu();
        licenciasConsultasMenu = new javax.swing.JMenuItem();
        placasConsultasMenu = new javax.swing.JMenuItem();
        reporteMenu = new javax.swing.JMenu();
        reporteGeneralReporteMenu = new javax.swing.JMenuItem();
        reporteBusquedaReporteMenu = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de Transito");

        tramitesMenu.setMnemonic('f');
        tramitesMenu.setText("Trámites");

        licenciaTramitesMenu.setMnemonic('o');
        licenciaTramitesMenu.setText("Licencia");
        tramitesMenu.add(licenciaTramitesMenu);

        placasTramitesMenu.setMnemonic('s');
        placasTramitesMenu.setText("Placas");
        tramitesMenu.add(placasTramitesMenu);

        menuBar.add(tramitesMenu);

        consultasMenu.setMnemonic('e');
        consultasMenu.setText("Consultas");

        licenciasConsultasMenu.setMnemonic('t');
        licenciasConsultasMenu.setText("Licencias");
        consultasMenu.add(licenciasConsultasMenu);

        placasConsultasMenu.setMnemonic('y');
        placasConsultasMenu.setText("Placas");
        consultasMenu.add(placasConsultasMenu);

        menuBar.add(consultasMenu);

        reporteMenu.setMnemonic('h');
        reporteMenu.setText("Reporte");

        reporteGeneralReporteMenu.setMnemonic('c');
        reporteGeneralReporteMenu.setText("Reporte de Trámites Realizados");
        reporteMenu.add(reporteGeneralReporteMenu);

        reporteBusquedaReporteMenu.setMnemonic('a');
        reporteBusquedaReporteMenu.setText("Reporte por busqueda");
        reporteMenu.add(reporteBusquedaReporteMenu);

        menuBar.add(reporteMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu consultasMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem licenciaTramitesMenu;
    private javax.swing.JMenuItem licenciasConsultasMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem placasConsultasMenu;
    private javax.swing.JMenuItem placasTramitesMenu;
    private javax.swing.JMenuItem reporteBusquedaReporteMenu;
    private javax.swing.JMenuItem reporteGeneralReporteMenu;
    private javax.swing.JMenu reporteMenu;
    private javax.swing.JMenu tramitesMenu;
    // End of variables declaration//GEN-END:variables

}
